# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Homepage 
# email: keywgh@gmail.com
work_email: wang9019@umn.edu
description: >- # this means to ignore newlines until "baseurl:"
  Nice to meat you.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://keywgh.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# facebook_username: keywgh
github_username:  keywgh
author: Ganghua Wang
google_analytics: UA-141229469-1
disqus:
  shortname: ghostw
# Build settings

theme: minima

markdown: kramdown
kramdown:
  math_engine: mathjax

algolia:
  application_id: H8IA69ZR1F
  index_name:     jekyll
  search_only_api_key: 92c9476a6e5b4957150781bfd6027bc9
  files_to_exclude: 
      - index.html
      - index.md
      - about/about.md
  # nodes_to_index: 'seminar'

header_pages: 
  - about/about.md
  - teach/index.md 
  # - other/index.md
  - blog/index.html

pagination:
  enabled: true
  per_page: 5
  permalink: '/:num.html'
  collection: 'posts'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2 # The number of links before the current page
    after: 2  # The number of links after the current page

plugins:
  - jekyll-feed
  - jemoji
  - jekyll-paginate-v2

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
